import type { NextPage } from "next";
import Head from "next/head";
import { ListaPreguntas } from "../components/Elements/ListaPreguntas/ListaPreguntas";
import { Header } from "../components/ui/Header";
import { AddPregunta } from "../components/User/AddPregunta/AddPregunta";
import { useAppSelector } from "../hooks";
import { useCheckAuth } from "../hooks/useCheckAuth";
import styles from "./Home.module.scss";

const Home: NextPage = () => {
  const status = useCheckAuth();

  const { active } = useAppSelector((state) => state.entries);
  console.log("active", active);
  return (
    <div>
      <Head>
        <title>Prototipo 1 - Centro de atención al lector</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <div className={styles.homeContainer}>
          <div className={styles.homeContainer__left}></div>
          <div className={styles.homeContainer__main}>
            <AddPregunta />
            <ListaPreguntas />
          </div>
          <div className={styles.homeContainer__right}></div>
        </div>
      </main>
    </div>
  );
};

export default Home;
