import type { NextPage } from "next";
import Head from "next/head";
import { useEffect } from "react";
import { ListaPreguntas } from "../components/Elements/ListaPreguntas/ListaPreguntas";
import { ListaSavedPreguntas } from "../components/Elements/ListaSavedPreguntas/ListaSavedPreguntas";
import { Header } from "../components/ui/Header/Header";
import { AddPregunta } from "../components/User/AddPregunta/AddPregunta";
import { useAppDispatch } from "../hooks";
import { useCheckAuth } from "../hooks/useCheckAuth";
import { startLoadingPreguntas } from "../store/entries";
import styles from "./Home.module.scss";

const Home: NextPage = () => {
  const dispatch = useAppDispatch();
  const status = useCheckAuth();
  useEffect(() => {
    dispatch(startLoadingPreguntas());
  }, []);
  return (
    <>
      <Head>
        <title>Prototipo 1 - Centro de atención al lector</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <div className={styles.homeContainer}>
          <div className={styles.homeContainer__left}></div>
          <div className={styles.homeContainer__main}>
            <AddPregunta />
            <ListaPreguntas />
          </div>
          <div className={styles.homeContainer__right}>
            <ListaSavedPreguntas status={status} />
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
