import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import { ListaPreguntas } from "../components/Elements/ListaPreguntas/ListaPreguntas";
import { ListaSavedPreguntas } from "../components/Elements/ListaSavedPreguntas/ListaSavedPreguntas";
import MostLiked from "../components/Elements/MostLiked/MostLiked";
import PreguntasSearch from "../components/Elements/preguntasSearch/PreguntasSearch";
import { Header } from "../components/ui/Header/Header";
import { AddPregunta } from "../components/User/AddPregunta/AddPregunta";
import { useAppDispatch } from "../hooks";
import { useCheckAuth } from "../hooks/useCheckAuth";
import { startLoadingPreguntas } from "../store/entries";
import styles from "./Home.module.scss";

const Home: NextPage = () => {
  const dispatch = useAppDispatch();
  const status = useCheckAuth();

  const [ query, setQuery ] = useState('')


  useEffect(() => {
    dispatch(startLoadingPreguntas());
  }, []);
  return (
    <>
      <Head>
        <title>Prototipo 1 - Centro de atención al lector</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <div className={styles.homeContainer}>
          <div className={styles.homeContainer__left}>
            <MostLiked/>
          </div>
          <div className={styles.homeContainer__main}>
            <AddPregunta />
            <PreguntasSearch setQuery={setQuery}/>
            <ListaPreguntas query={query}/>
          </div>
          <div className={styles.homeContainer__right}>
            <ListaSavedPreguntas status={status} />
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
